---
permalink: sg6000/index.html 
sidebar: sidebar 
keywords: storagegrid, sg6000, storage node, storage appliance, maintain, maintaining, hardware, procedures, tasks 
summary: Möglicherweise müssen Sie auf der SG6000-Appliance Wartungsarbeiten durchführen. Bei den in diesem Abschnitt beschriebenen Verfahren wird davon ausgegangen, dass die Appliance bereits als Storage-Node in einem StorageGRID-System bereitgestellt wurde. 
---
= Warten Sie die SG6000-Appliance
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie auf der SG6000-Appliance Wartungsarbeiten durchführen.

In diesem Abschnitt wird davon ausgegangen, dass die Appliance bereits als Speicher-Node in einem StorageGRID-System bereitgestellt wurde.

Siehe link:../commonhardware/index.html["Allgemeine Verfahren"] Für Wartungsverfahren, die von allen Geräten verwendet werden.

Siehe link:../installconfig/configuring-hardware.html["Richten Sie die Hardware ein"] Für Wartungsverfahren, die auch während der Erstinstallation und -Konfiguration der Appliance durchgeführt werden.

Um Serviceunterbrechungen zu vermeiden, vergewissern Sie sich, dass alle anderen Speicherknoten mit dem Raster verbunden sind, bevor Sie das Gerät herunterfahren oder das Gerät während eines geplanten Wartungsfensters herunterfahren, wenn die Serviceunterbrechungen akzeptabel sind. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/storagegrid-118/monitor/monitoring-system-health.html#monitor-node-connection-states["Monitoring der Verbindungsstatus der Nodes"^].


CAUTION: Wenn Sie jemals eine ILM-Regel verwendet haben, die nur eine Kopie eines Objekts erstellt, müssen Sie die Appliance während eines geplanten Wartungsfensters herunterfahren. Andernfalls verlieren Sie während des Wartungsvorgangs, die einen Storage-Node außer Betrieb nimmt, möglicherweise vorübergehend den Zugriff auf diese Objekte. Weitere Informationen finden Sie unter https://docs.netapp.com/us-en/storagegrid-118/ilm/index.html["Verwalten von Objekten mit Information Lifecycle Management"^].
