---
sidebar: sidebar 
permalink: storagegrid-enable.html 
keywords: storagegrid, how to enable, third-party solutions, tools, applications, examples 
summary: Erfahren Sie, wie Sie Applikationen in Ihrer StorageGRID Umgebung testen und aktivieren. 
---
= StorageGRID -Lösungen und -Ressourcen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Gehe zu https://docs.netapp.com/us-en/storagegrid-enable/index.html["StorageGRID -Lösungen und -Ressourcen"^] um zu erfahren, wie Sie Anwendungen in Ihrer StorageGRID Umgebung testen und aktivieren.

* StorageGRID -Lösungen und -Ressourcen* bietet Beispiele und Kochbücher, die die Produktdokumentation auf dieser Site erweitern, und beschreibt einige der nächsten Schritte bei der Bewertung und Integration mit StorageGRID.

Einige der Informationen enthalten:

* Liste validierter Lösungen von Drittanbietern für frühere und aktuelle StorageGRID Versionen.
* Produktfunktionshandbücher. Diese Leitfäden bieten beispielsweise alle Informationen, die Sie zum Erstellen von Cloud-Speicherpools benötigen.
* Tool- und Anwendungsleitfäden.
* API-Beispiele zur Verwendung von StorageGRID Funktionen wie S3-Verschlüsselung und S3-Objektsperre.

