---
permalink: sg6200/index.html 
sidebar: sidebar 
keywords: storagegrid, sg6200 storage appliance, SGF6212 storage appliance, maintain, maintaining, hardware, procedures, tasks 
summary: Möglicherweise müssen Sie Wartungsarbeiten an Ihrem Appliance durchführen. Verfahren, die speziell für die Wartung Ihres sg6200 Appliance relevant sind, finden Sie in diesem Abschnitt. 
---
= SG6200-Gerät warten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie Wartungsarbeiten an Ihrem Gerät durchführen. Die spezifischen Wartungsanweisungen für Ihr SG6200-Gerät finden Sie in diesem Abschnitt.

Bei den in diesem Abschnitt beschriebenen Verfahren wird davon ausgegangen, dass die Appliance bereits als Storage-Node in einem StorageGRID-System bereitgestellt wurde.

*Wartungskonfigurationsverfahren* werden über den Appliance Installer, Grid Manager oder die BMC-Schnittstelle durchgeführt. Hierzu gehören folgende Verfahren:

* link:turning-sg6200-identify-led-on-and-off.html["Schalten Sie die Appliance Identify-LED ein und aus"]
* link:locating-sg6200-in-data-center.html["Suchen Sie die Appliance im Datacenter"]
* link:power-sg6200-off-on.html["Schalten Sie das Gerät aus"]
* link:changing-link-configuration-of-sg6200-appliance.html["Ändern Sie die Link-Konfiguration der Appliance"]


*Für die Hardware-Wartungsverfahren* ist die physische Manipulation bestimmter SGF6212- oder SG6260-Komponenten erforderlich.



== Upgrade der Laufwerk-Firmware

Die Firmware der Laufwerke in der und SG6260 wird bei jedem Neustart des Systems automatisch überprüft. Bei Bedarf wird die Firmware automatisch auf die von der aktuellen StorageGRID-Version erwartete Version aktualisiert. Firmware-Aktualisierungen erfolgen üblicherweise im Rahmen von StorageGRID-Software-Upgrades. Alle notwendigen Firmware-Aktualisierungen für bestehende StorageGRID-Versionen werden in Hotfixes bereitgestellt. Befolgen Sie die Anweisungen in jedem Hotfix, um sicherzustellen, dass die Aktualisierung auf allen Laufwerken angewendet wird, die davon profitieren könnten.

Darüber hinaus können die Laufwerke im SG6260 über SANtricity mithilfe der link:upgrading-drive-firmware-using-santricity-system-manager-online.html["SANtricity System Manager online"] oder link:upgrading-drive-firmware-using-santricity-system-manager-offline.html["SANtricity System Manager offline"] Prozeduren aktualisiert werden.


NOTE: Für die Wartung des SGF6212-Geräts wird kein SANtricity System Manager benötigt.



== Allgemeine Wartungsverfahren

Siehe link:../commonhardware/index.html["Allgemeine Wartungsverfahren"] Für Verfahren, die für alle Appliances gleich sind, wie z. B. das Anwenden eines Hotfix, das Wiederherstellen eines Knotens oder Standorts und das Durchführen von Netzwerkwartungen.

Siehe link:../installconfig/configuring-hardware.html["Appliance-Hardware einrichten"] Für Gerätewartungsverfahren, die auch während der Erstinstallation und -Konfiguration der Appliance durchgeführt werden.
