---
permalink: sg6200/replace-cmos-in-sg6200.html 
sidebar: sidebar 
keywords: storagegrid, sg6200, SGF6212, storage node, storage appliance, Replacing, replace, CMOS, battery, sg6260 
summary: Gehen Sie wie folgt vor, um die CMOS-Knopfzellenbatterien auf der Systemplatine auszutauschen. 
---
= Ersetzen Sie die CMOS-Batterien von SGF6212 oder SG6200-CN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Gehen Sie wie folgt vor, um die CMOS-Knopfzellenbatterien auf der Systemplatine auszutauschen.

.Über diese Aufgabe
Um Serviceunterbrechungen zu vermeiden, vergewissern Sie sich, dass alle anderen Storage Nodes mit dem Grid verbunden sind, bevor Sie mit dem Austausch der CMOS-Batterie beginnen, oder tauschen Sie die Batterien während eines geplanten Wartungsfensters aus, wenn Serviceunterbrechungen akzeptabel sind. Siehe die Informationen über https://docs.netapp.com/us-en/storagegrid/monitor/monitoring-system-health.html#monitor-node-connection-states["Monitoring der Verbindungsstatus der Nodes"^].


CAUTION: Wenn Sie jemals eine ILM-Regel verwendet haben, die nur eine Kopie eines Objekts erstellt, müssen Sie die Batterien während eines geplanten Wartungsfensters ersetzen, da Sie während dieses Vorgangs möglicherweise vorübergehend keinen Zugriff auf diese Objekte haben. Siehe Informationen über https://docs.netapp.com/us-en/storagegrid/ilm/why-you-should-not-use-single-copy-replication.html["Warum sollten Sie die Single-Copy-Replizierung nicht verwenden"^].

.Bevor Sie beginnen
* Du hast link:verify-component-to-replace.html["Das Gerät, bei dem die CMOS-Batterien ausgetauscht werden müssen, wurde überprüft"].
* Sie haben link:locating-sg6200-in-data-center.html["physisch platziertes SGF6212 Appliance oder SG6200-CN Controller"]wo im Rechenzentrum die CMOS-Batterien ausgetauscht werden müssen.
* Sie haben die aktuelle BMC-Konfiguration der Appliance aufgezeichnet, sofern sie weiterhin verfügbar ist.
+
.. Melden Sie sich bei der zu ersetzenden Appliance an:
+
... Geben Sie den folgenden Befehl ein: `ssh admin@_grid_node_IP_`
... Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
... Geben Sie den folgenden Befehl ein, um zum Root zu wechseln: `su -`
... Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
+
Wenn Sie als root angemeldet sind, ändert sich die Eingabeaufforderung von `$` Bis `#`.



.. Geben Sie ein: `*run-host-command ipmitool lan print*` Um die aktuelle BMC-Konfiguration für die Appliance anzuzeigen.
+

NOTE: Ein link:power-sg6200-off-on.html#shut-down-the-sgf6212-appliance-or-sg6200-cn-controller["Kontrolliertes Herunterfahren des Geräts"] ist erforderlich, bevor das Gerät aus dem Rack entfernt wird.



* Sie haben alle Kabel getrennt und link:reinstalling-sg6200-cover.html["Die Geräteabdeckung entfernt"].


.Schritte
. Wickeln Sie das Gurt-Ende des ESD-Armbands um Ihr Handgelenk, und befestigen Sie das Clip-Ende auf einer Metallmasse, um eine statische Entladung zu verhindern.
. Entfernen Sie die erste CMOS-Batterie.
+
.. Suchen Sie die CMOS-Batterie auf der Systemplatine.
.. Drücken Sie den Halteclip mit dem Finger oder einem Kunststoffhebelwerkzeug von der Batterie weg, um ihn aus der Steckdose zu fecken.
+
image::../media/drw_s2025_cmos_battery_replace_ieops-2558.svg[Entfernen einer CMOS-Batterie von der Systemplatine]

.. Entfernen Sie die Batterie, und entsorgen Sie sie ordnungsgemäß.


. Setzen Sie die Ersatz-CMOS-Batterie ein.
+
.. Nehmen Sie die Ersatz-CMOS-Batterie aus ihrer Verpackung.
.. Drücken Sie den Ersatzakku mit der positiven (+) Seite nach oben in den leeren Sockel auf der Systemplatine, bis der Akku einrastet.


. Wiederholen Sie diese Schritte für die zweite CMOS-Batterie.
. Wenn Sie keine weiteren Wartungsmaßnahmen im Gerät durchführen müssen, setzen Sie die Geräteabdeckung wieder ein, bringen Sie das Gerät wieder in das Rack ein, schließen Sie die Kabel an und schalten Sie das Gerät mit Strom aus.
. Wenn die Laufwerkverschlüsselung für die SED-Laufwerke auf der ersetzten Appliance aktiviert war, müssen Sie dies tun link:../installconfig/optional-enabling-node-encryption.html#access-an-encrypted-drive["Geben Sie die Passphrase für die Laufwerkverschlüsselung ein"] So greifen Sie auf die verschlüsselten Laufwerke zu, wenn die Ersatz-Appliance zum ersten Mal gestartet wird.
. Wenn die von Ihnen ersetzte Appliance einen Verschlüsselungsmanagement-Server (KMS) zum Management der Schlüssel für die Node-Verschlüsselung verwendet hat, ist möglicherweise eine zusätzliche Konfiguration erforderlich, bevor der Node dem Grid beitreten kann. Wenn der Node nicht automatisch in das Raster integriert wird, stellen Sie sicher, dass diese Konfigurationseinstellungen auf die neue Appliance übertragen wurden, und konfigurieren Sie manuell alle Einstellungen, die nicht über die erwartete Konfiguration verfügen:
+
** link:../installconfig/accessing-storagegrid-appliance-installer.html["Konfigurieren Sie StorageGRID-Verbindungen"]
** https://docs.netapp.com/us-en/storagegrid/admin/kms-overview-of-kms-and-appliance-configuration.html#set-up-the-appliance["Konfigurieren Sie die Node-Verschlüsselung für die Appliance"^]


. Melden Sie sich bei der Appliance an:
+
.. Geben Sie den folgenden Befehl ein: `ssh admin@_grid_node_IP_`
.. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
.. Geben Sie den folgenden Befehl ein, um zum Root zu wechseln: `su -`
.. Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:


. Stellen Sie die BMC-Netzwerkverbindung für das Gerät mithilfe einer der folgenden Optionen wieder her:
+
** Verwenden Sie statische IP, Netzmaske und Gateway
** Verwenden Sie DHCP, um eine IP, eine Netzmaske und ein Gateway zu erhalten
+
... Geben Sie zum Wiederherstellen der BMC-Konfiguration für die Verwendung einer statischen IP, Netzmaske und eines Gateways die folgenden Befehle ein:
+
`*run-host-command ipmitool lan set 1 ipsrc static*`

+
`*run-host-command ipmitool lan set 1 ipaddr _Appliance_IP_*`

+
`*run-host-command ipmitool lan set 1 netmask _Netmask_IP_*`

+
`*run-host-command ipmitool lan set 1 defgw ipaddr _Default_gateway_*`

... Geben Sie den folgenden Befehl ein, um die BMC-Konfiguration so wiederherzustellen, dass DHCP zum Abrufen einer IP, einer Netmask und eines Gateways verwendet wird:
+
`*run-host-command ipmitool lan set 1 ipsrc dhcp*`





. Stellen Sie nach dem Wiederherstellen der BMC-Netzwerkverbindung eine Verbindung zur BMC-Schnittstelle her, um die zusätzlich angewendete benutzerdefinierte BMC-Konfiguration zu prüfen und wiederherzustellen. Sie sollten beispielsweise die Einstellungen für SNMP-Trap-Ziele und E-Mail-Benachrichtigungen bestätigen. Siehe link:../installconfig/configuring-bmc-interface.html["Konfigurieren Sie die BMC-Schnittstelle"].
. Vergewissern Sie sich, dass der Appliance-Node im Grid Manager angezeigt wird und keine Meldungen angezeigt werden.

