---
permalink: installconfig/configuring-hardware.html 
sidebar: sidebar 
keywords: storage node, storage appliance, hardware, configure, configuration, set up, setup, network, networking 
summary: Nachdem Sie die Appliance mit Strom versorgt haben, konfigurieren Sie die Netzwerkverbindungen, die von StorageGRID verwendet werden.  
---
= StorageGRID Gerätehardware einrichten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie die Appliance mit Strom versorgt haben, konfigurieren Sie die Netzwerkverbindungen, die von StorageGRID verwendet werden.



== Erforderliche Hardwarekonfigurationen



=== Netzwerkverbindungen

Sie müssen die erforderlichen Netzwerkverbindungen für alle Geräte konfigurieren und überprüfen:

* link:../installconfig/accessing-storagegrid-appliance-installer.html["Greifen Sie auf den Appliance Installer zu"]
* link:../installconfig/configuring-network-links.html["Netzwerkverbindungen konfigurieren"]
* link:../installconfig/verifying-port-level-network-connections.html["Überprüfen Sie Netzwerkverbindungen auf Portebene"]




=== BMC Schnittstelle

Sie müssen link:../installconfig/configuring-bmc-interface.html["Konfigurieren Sie die Baseboard Management Controller (BMC)-Schnittstelle"] , wenn Sie eines der folgenden Geräte installieren:

* SG100
* SG110
* SG120
* SG1000
* SG1100
* SG1200
* SGF6024
* SGF6112
* SGF6212
* SG6060
* SG6160
* SG6260


Über die BMC-Schnittstelle können Sie SNMP und andere grundlegende Einstellungen für Ihre Appliances konfigurieren. Sie ermöglicht Ihnen außerdem, Ihre Hardwareinstallation zu überprüfen, den Betriebszustand Ihrer Appliance zu bestimmen und die Identify-LED an Ihrer Appliance zu steuern.

Weitere Informationen zu den Funktionen, die Sie mit dem BMC nutzen können, finden Sie unter link:../commonhardware/use-bmc.html["Verwenden Sie die BMC-Schnittstelle"].



== Optionale Hardwarekonfigurationen



=== SANtricity System Manager

Sie können link:../installconfig/accessing-and-configuring-santricity-system-manager.html["SANtricity System Manager konfigurieren"], wenn Sie eines der folgenden Geräte besitzen:

* SG5712
* SG5760
* SG5812
* SG5860
* SGF6024
* SG6060
* SG6160
* SG6260


SANtricity System Manager software ermöglicht Ihnen Folgendes:

* Überwachen Sie Systemleistungsdaten, den Status der Hardwarekomponenten und die Supportfunktionen Ihres Geräts
* Verwalten Sie Laufwerkssicherheitsschlüssel, SNMP- und syslog-Warnungen sowie Administratorkennwörter für den Zugriff auf SANtricity System Manager
* Zugriff auf die E-Series AutoSupport konfigurieren




=== Aktivieren Sie die Node- oder Laufwerkverschlüsselung

Sie können link:../installconfig/optional-enabling-node-encryption.html["Knoten- oder Laufwerkverschlüsselung aktivieren"] verwenden, um die Laufwerke und Festplatten in Ihrem Gerät zu schützen.



=== RAID-Modus ändern

Sie können link:../installconfig/optional-changing-raid-mode.html["Ändern Sie den RAID-Modus Ihres Storage Appliance."] erfüllen, um Ihre Speicher- und Wiederherstellungsanforderungen zu berücksichtigen.

Folgende Geräte unterstützen die Änderung des RAID-Modus:

* SG5760
* SG5860
* SGF6024
* SG6060
* SG6160
* SG6260




=== Netzwerkports neu zuordnen

Sie können link:../installconfig/optional-remapping-network-ports-for-appliance.html["Ordnen Sie die Netzwerkports Ihres Geräts neu zu"] verwenden, um Ihre Netzwerkverbindungen zu optimieren.
