---
permalink: installconfig/monitoring-appliance-installation.html 
sidebar: sidebar 
keywords: appliance, installation, install, progress, monitor, status 
summary: Das Installationsprogramm der StorageGRID Appliance stellt den Status bereit, bis die Installation abgeschlossen ist. Nach Abschluss der Softwareinstallation wird die Appliance neu gestartet. 
---
= Installation der StorageGRID-Appliance überwachen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Das Installationsprogramm der StorageGRID Appliance stellt den Status bereit, bis die Installation abgeschlossen ist. Nach Abschluss der Softwareinstallation wird die Appliance neu gestartet.

.Schritte
[role="tabbed-block"]
====
.Storage Appliance
--
. Um den Installationsfortschritt zu überwachen, klicken Sie auf *Installation überwachen*.
+
Auf der Seite Monitor-Installation wird der Installationsfortschritt angezeigt.

+
Die blaue Statusleiste zeigt an, welche Aufgabe zurzeit ausgeführt wird. Grüne Statusleisten zeigen Aufgaben an, die erfolgreich abgeschlossen wurden.

+

NOTE: Das Installationsprogramm stellt sicher, dass Aufgaben, die in einer früheren Installation ausgeführt wurden, nicht erneut ausgeführt werden. Wenn Sie eine Installation erneut ausführen, werden alle Aufgaben, die nicht erneut ausgeführt werden müssen, mit einer grünen Statusleiste und dem Status „`übersprungen`“ angezeigt.

. Überprüfen Sie den Fortschritt der ersten beiden Installationsphasen.
+
*1. Speicher konfigurieren*

+
Während dieser Phase stellt das Installationsprogramm eine Verbindung zum Speicher-Controller her, löscht alle vorhandenen Konfigurationen, erstellt Raids gemäß dem konfigurierten RAID-Modus, weist Volumes für die StorageGRID-Software und den Objektdatenspeicher zu und konfiguriert Hosteinstellungen.

+
*2. Installieren Sie das Betriebssystem*

+
In dieser Phase kopiert das Installationsprogramm das Betriebssystem-Image für StorageGRID auf die Appliance.

. Überwachen Sie den Installationsfortschritt weiter, bis die Phase *Install StorageGRID* angehalten wird und auf der eingebetteten Konsole eine Meldung angezeigt wird, in der Sie aufgefordert werden, diesen Knoten auf dem Admin-Knoten mithilfe des Grid Managers zu genehmigen. Fahren Sie dann mit dem nächsten Schritt fort.
. https://docs.netapp.com/us-en/storagegrid/admin/signing-in-to-grid-manager.html["Wechseln Sie zum Grid-Manager"^]des primären Admin-Knotens, genehmigen Sie den ausstehenden Speicherknoten und schließen Sie den StorageGRID -Installationsprozess ab.
+
Wenn Sie im Grid Manager auf *Installieren* klicken, wird Stufe 3 abgeschlossen und Stufe 4, *Installation abschließen*, beginnt. Wenn Phase 4 abgeschlossen ist, wird der Controller neu gestartet.



Schließen Sie das Fenster, nachdem alle Installationsschritte abgeschlossen sind.

--
.Service-Appliance
--
. Um den Installationsfortschritt zu überwachen, klicken Sie auf *Installation überwachen*.
+
Auf der Seite Monitor-Installation wird der Installationsfortschritt angezeigt.

+
Die blaue Statusleiste zeigt an, welche Aufgabe zurzeit ausgeführt wird. Grüne Statusleisten zeigen Aufgaben an, die erfolgreich abgeschlossen wurden.

+

NOTE: Das Installationsprogramm stellt sicher, dass Aufgaben, die in einer früheren Installation ausgeführt wurden, nicht erneut ausgeführt werden. Wenn Sie eine Installation erneut ausführen, werden alle Aufgaben, die nicht erneut ausgeführt werden müssen, mit einer grünen Statusleiste und dem Status „`übersprungen`“ angezeigt.

. Überprüfen Sie den Fortschritt der ersten beiden Installationsphasen.
+
*1. Speicher konfigurieren*

+
In dieser Phase löscht das Installationsprogramm alle vorhandenen Konfigurationen von den Laufwerken in der Appliance und konfiguriert die Hosteinstellungen.

+
*2. Installieren Sie das Betriebssystem*

+
In dieser Phase kopiert das Installationsprogramm das Betriebssystem-Image für StorageGRID auf die Appliance.

. Fahren Sie mit der Überwachung des Installationsfortschritts fort, bis einer der folgenden Prozesse erfolgt ist:
+
** Für alle Appliance-Knoten außer dem primären Admin-Knoten wird die Phase „StorageGRID installieren“ angehalten und auf der eingebetteten Konsole wird eine Meldung angezeigt, in der Sie aufgefordert werden, diesen Knoten auf dem Admin-Knoten mithilfe des https://docs.netapp.com/us-en/storagegrid/admin/signing-in-to-grid-manager.html["Grid Manager"^] ; fahren Sie dann mit dem nächsten Schritt fort.
** Für die Installation des primären Admin-Knotens der Appliance müssen Sie den Knoten nicht genehmigen. Das Gerät wird neu gestartet. Sie können den nächsten Schritt überspringen.
+

NOTE: Während der Installation eines primären Admin-Knotens der Appliance wird eine fünfte Phase angezeigt, in der der StorageGRID-Installer geladen wird (der Beispielbildschirm zeigt nur die ersten vier Phasen). Wenn der StorageGRID-Installer (fünfte Phase) länger als 10 Minuten geladen wird, aktualisieren Sie die Webseite manuell.



. https://docs.netapp.com/us-en/storagegrid/admin/signing-in-to-grid-manager.html["Wechseln Sie zum Grid-Manager"^] Genehmigen Sie den ausstehenden Grid-Knoten des primären Admin-Knotens, und schließen Sie den StorageGRID-Installationsvorgang ab.
+
Wenn Sie im Grid Manager auf *Installieren* klicken, wird Stufe 3 abgeschlossen und Stufe 4, *Installation abschließen*, beginnt. Wenn Phase 4 abgeschlossen ist, wird das Gerät neu gestartet.



Schließen Sie das Fenster, nachdem alle Installationsschritte abgeschlossen sind.

--
====