---
permalink: installconfig/reviewing-appliance-network-connections.html 
sidebar: sidebar 
keywords: network connections, appliance, grid, admin, client, bmc, management 
summary: Vor der Installation der StorageGRID Appliance sollten Sie wissen, welche Netzwerke mit der Appliance verbunden werden können. 
---
= StorageGRID-Netzwerktypen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Vor der Installation der StorageGRID Appliance sollten Sie wissen, welche Netzwerke mit der Appliance verbunden werden können und wie die Ports auf den einzelnen Controllern verwendet werden. Die Netzwerkanforderungen von StorageGRID werden im ausführlich erläutert https://docs.netapp.com/us-en/storagegrid-118/network/index.html["Netzwerkrichtlinien"^].

Lesen Sie die Anweisungen für Ihr Gerät, um herauszufinden, welche Informationen Sie benötigen:

* link:gathering-installation-information-sg100-and-sg1000.html["SG100 und SG1000"]
* link:gathering-installation-information-sg5700.html["SG5700"]
* link:gathering-installation-information-sg6000.html["SG6000"]
* link:gathering-installation-information-sg6100.html["SG6100"]


Alternativ können Sie mit Ihrem NetApp Professional Services Consultant zusammenarbeiten, um die Konfigurationsschritte mit dem NetApp ConfigBuilder Tool zu optimieren und zu automatisieren. Siehe link:automating-appliance-installation-and-configuration.html["Automatisierung der Appliance-Installation und -Konfiguration"].

Wenn Sie eine StorageGRID Appliance als Node in einem StorageGRID System implementieren, können Sie eine Verbindung mit folgenden Netzwerken herstellen:

* *Grid-Netzwerk für StorageGRID*: Das Grid-Netzwerk wird für den gesamten internen StorageGRID-Datenverkehr verwendet. Das System bietet Konnektivität zwischen allen Nodes im Grid und allen Standorten und Subnetzen. Das Grid-Netzwerk ist erforderlich.
* *Admin-Netzwerk für StorageGRID*: Das Admin-Netzwerk ist ein geschlossenes Netzwerk, das zur Systemadministration und Wartung verwendet wird. Das Admin-Netzwerk ist in der Regel ein privates Netzwerk und muss nicht zwischen Standorten routingfähig sein. Das Admin-Netzwerk ist optional.
* *Client-Netzwerk für StorageGRID:* das Client-Netzwerk ist ein offenes Netzwerk, das für den Zugriff auf Client-Anwendungen, einschließlich S3 und Swift, verwendet wird. Das Client-Netzwerk ermöglicht den Zugriff auf das Grid-Protokoll, sodass das Grid-Netzwerk isoliert und gesichert werden kann. Sie können das Client-Netzwerk so konfigurieren, dass über dieses Netzwerk nur über die Ports zugegriffen werden kann, die Sie öffnen möchten. Das Client-Netzwerk ist optional.
* *Managementnetzwerk für SANtricity* (optional für Speichergeräte, nicht für SG6100 erforderlich): Dieses Netzwerk bietet Zugriff auf SANtricity System Manager, mit dem Sie die Hardwarekomponenten im Appliance- und Speicher-Controller-Shelf überwachen und verwalten können. Dieses Managementnetzwerk kann das gleiche sein wie das Admin-Netzwerk für StorageGRID, oder es kann ein unabhängiges Managementnetzwerk sein.
* *BMC-Managementnetzwerk* (optional für SG100, SG1000, SG6000 und SG6100): Dieses Netzwerk bietet Zugriff auf den Baseboard Management Controller in den SG100, SG1000, SG6000 und SG6100 Appliances, sodass Sie die Hardwarekomponenten in der Appliance überwachen und verwalten können. Dieses Managementnetzwerk kann das gleiche sein wie das Admin-Netzwerk für StorageGRID, oder es kann ein unabhängiges Managementnetzwerk sein.
+
Wenn das optionale BMC-Managementnetzwerk nicht verbunden ist, sind einige Support- und Wartungsverfahren schwieriger zu bewältigen. Sie können das BMC-Managementnetzwerk außer zu Supportzwecken unverbunden lassen.




NOTE: Ausführliche Informationen zu StorageGRID-Netzwerken finden Sie im https://docs.netapp.com/us-en/storagegrid-118/network/storagegrid-network-types.html["StorageGRID-Netzwerktypen"^].
