---
permalink: sg6100/index.html 
sidebar: sidebar 
keywords: storagegrid, sg6100 storage appliance, SGF6112 storage appliance, maintain, maintaining, hardware, procedures, tasks 
summary: Möglicherweise müssen Sie Wartungsmaßnahmen an Ihrem Gerät durchführen. In diesem Abschnitt finden Sie spezifische Verfahren zur Wartung Ihrer SG6100 Appliance. 
---
= SG6100 Appliance warten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie Wartungsmaßnahmen an Ihrem Gerät durchführen. In diesem Abschnitt finden Sie spezifische Verfahren zur Wartung Ihrer SG6100 Appliance.

Bei den in diesem Abschnitt beschriebenen Verfahren wird davon ausgegangen, dass die Appliance bereits als Storage-Node in einem StorageGRID-System bereitgestellt wurde.

*Konfigurationswartungsverfahren* werden über den Appliance Installer, Grid Manager oder die BMC-Schnittstelle durchgeführt. Hierzu gehören folgende Verfahren:

* link:turning-sgf6112-identify-led-on-and-off.html["Schalten Sie die Appliance Identify-LED ein und aus"]
* link:locating-sgf6112-in-data-center.html["Suchen Sie die Appliance im Datacenter"]
* link:power-sgf6112-off-on.html["Schalten Sie das Gerät aus"]
* link:changing-link-configuration-of-sgf6112-appliance.html["Ändern Sie die Link-Konfiguration der Appliance"]


*Hardware-Wartungsverfahren* erfordern die physische Manipulation bestimmter SGF6112-Komponenten.



== Upgrade der Laufwerk-Firmware

Die Firmware auf den Laufwerken im SGF6112 wird bei jedem Neustart des Geräts automatisch überprüft. Bei Bedarf wird die Firmware automatisch auf die Version aktualisiert, die von der aktuellen StorageGRID-Version erwartet wird. Firmware-Upgrades erfolgen in der Regel während Upgrades der StorageGRID Software. Alle notwendigen Upgrades der Laufwerk-Firmware für bestehende StorageGRID-Versionen werden in Hotfixes integriert. Befolgen Sie die Anweisungen, die jedem Hotfix beiliegen, um sicherzustellen, dass das Upgrade auf alle Laufwerke angewendet wird, die davon profitieren könnten.


NOTE: SANtricity System Manager ist nicht für die Wartung der SGF6112 Appliance erforderlich.



== Allgemeine Wartungsverfahren

Siehe link:../commonhardware/index.html["Allgemeine Wartungsverfahren"] Für Verfahren, die für alle Appliances gleich sind, wie z. B. das Anwenden eines Hotfix, das Wiederherstellen eines Knotens oder Standorts und das Durchführen von Netzwerkwartungen.

Siehe link:../installconfig/configuring-hardware.html["Appliance-Hardware einrichten"] Für Gerätewartungsverfahren, die auch während der Erstinstallation und -Konfiguration der Appliance durchgeführt werden.
