---
permalink: sg6100/replace-6160-drives-60.html 
sidebar: sidebar 
keywords: E4000 replace drive, replacing E4000 drive, E4000 replace drive, replacing E4000 drive, E4000, sg6160, sg6100cn 
summary: Ersetzen Sie ein Laufwerk in einem E4000 durch ein Shelf mit 60 Laufwerken. 
---
= Ersetzen von Laufwerken im Storage-Controller-Shelf oder Erweiterungs-Shelf (SG6160)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Laufwerk in einem SG6160 Storage-Controller-Shelf oder Erweiterungs-Shelf (DE460C) ersetzen.

.Über diese Aufgabe
StorageGRID Grid Manager überwacht den Status des Storage Arrays und gibt bei Laufwerksausfällen Warnmeldungen aus.  Wenn der Grid Manager eine Warnmeldung ausgibt, oder Sie können den Recovery Guru im SANtricity System Manager verwenden, um weitere Informationen über das jeweilige Laufwerk zu erhalten, das ausgefallen ist.  Wenn ein Laufwerk ausfällt, leuchtet die gelbe Warn-LED. Sie können ein ausgefallenes Laufwerk im laufenden Betrieb austauschen, während das Speicher-Array I/O-Vorgänge empfängt

.Bevor Sie beginnen
* Überprüfen Sie die Anforderungen für die Laufwerksverwaltung.
* Stellen Sie sicher, dass Sie Folgendes haben:
+
** Ein von NetApp unterstütztes Ersatzlaufwerk für Ihr Controller Shelf oder Festplatten-Shelf.
** Ein ESD-Armband, oder Sie haben andere antistatische Vorsichtsmaßnahmen getroffen.
** Zugriff auf den SANtricity System Manager:
+
*** Wählen Sie im Grid-Manager *NODES* > *_Appliance Node_* > *SANtricity System Manager* aus. Informationen zum Controller finden Sie auf der https://docs.netapp.com/us-en/storagegrid/monitor/viewing-santricity-system-manager-tab.html["Registerkarte „SANtricity System Manager“"].
*** Zeigen Sie einen Browser in der Management Station auf den Domänennamen oder die IP-Adresse des Controllers.








== Schritt 1: Vorbereitung auf den Austausch des Laufwerks

Bereiten Sie sich auf den Austausch eines Laufwerks vor, indem Sie den Recovery Guru in SANtricity System Manager prüfen und alle erforderlichen Schritte ausführen. Dann können Sie die ausgefallene Komponente finden.

.Schritte
. Wenn der Recovery Guru im SANtricity System Manager Sie über einen _bevorstehenden Laufwerksausfall informiert hat_, aber es ist noch nicht ausgefallen, befolgen Sie die Anweisungen im Recovery Guru zum Fehlschlagen des Laufwerks.
. Überprüfen Sie bei Bedarf mit SANtricity System Manager, ob Sie ein geeignetes Ersatzlaufwerk besitzen.
+
.. Wählen Sie *Hardware*.
.. Wählen Sie in der Shelf-Grafik das ausgefallene Laufwerk aus.
.. Klicken Sie auf das Laufwerk, um das Kontextmenü anzuzeigen, und wählen Sie dann *Einstellungen anzeigen*.
.. Vergewissern Sie sich, dass die Kapazität des Ersatzlaufwerks dem des Ersatzlaufwerks entspricht oder höher ist als das ersetzte Laufwerk und dass es die Funktionen besitzt, die Sie erwarten.


. Verwenden Sie bei Bedarf SANtricity System Manager, um das Laufwerk innerhalb des Storage-Arrays zu finden.
+
.. Entfernen Sie das Shelf mit einer Blende, damit Sie die LEDs sehen.
.. Wählen Sie im Kontextmenü des Laufwerks die Option *Positionsanzeige einschalten*.
+
Die Warn-LED (gelb) der Laufwerksschublade blinkt, damit Sie das richtige Laufwerk öffnen können, um zu ermitteln, welches Laufwerk ersetzt werden soll.



. Entriegeln Sie die Antriebsschublade, indem Sie an beiden Hebeln ziehen.
+
.. Ziehen Sie die Antriebsschublade vorsichtig mit den ausgestreckte Hebeln heraus, bis sie einrastet.
.. Suchen Sie oben in der Laufwerksschublade, um die Warn-LED vor jedem Laufwerk zu finden.
+
Die Warn-LEDs der Laufwerksschublade befinden sich auf der linken Seite vor jedem Laufwerk, wobei ein Warnsymbol auf dem Laufwerkgriff direkt hinter der LED leuchtet.







== Schritt 2: Entfernen Sie ausgefallenes Laufwerk

Entfernen Sie ein ausgefallenes Laufwerk, um es durch ein neues zu ersetzen.

.Schritte
. Packen Sie das Ersatzlaufwerk aus, und stellen Sie es auf eine flache, statische Oberfläche in der Nähe des Regals ein.
+
Speichern Sie alle Verpackungsmaterialien für das nächste Mal, wenn Sie eine Fahrt zurückschicken müssen.

. Lösen Sie die Hebel der Antriebsschublade von der Mitte der entsprechenden Antriebsschublade, indem Sie beide zur Seite der Schublade ziehen.
. Ziehen Sie die Hebel der erweiterten Laufwerkschublade vorsichtig heraus, um die Laufwerkschublade bis zur vollständigen Erweiterung zu ziehen, ohne sie aus dem Gehäuse zu entfernen.
. Ziehen Sie vorsichtig die orangefarbene Entriegelungsriegel vor dem zu entfernenden Laufwerk nach hinten.
+
Der Nockengriff an den Antriebsfedern öffnet sich teilweise und der Antrieb wird aus der Schublade gelöst.

. Den Nockengriff öffnen und den Antrieb leicht herausheben.
. Warten Sie 30 Sekunden.
. Heben Sie den Antrieb mithilfe des Nockengriffs aus dem Regal.
. Setzen Sie das Laufwerk auf eine antistatische, gepolsterte Oberfläche, die von Magnetfeldern entfernt ist.
. Warten Sie 30 Sekunden, bis die Software erkennt, dass das Laufwerk entfernt wurde.
+

NOTE: Wenn Sie versehentlich ein aktives Laufwerk entfernen, warten Sie mindestens 30 Sekunden, und installieren Sie es erneut. Informationen zum Recovery-Verfahren finden Sie in der Storage Management Software.





== Schritt 3: Neues Laufwerk installieren

Installieren Sie ein neues Laufwerk, um das ausgefallene zu ersetzen.


CAUTION: Installieren Sie das Ersatzlaufwerk so schnell wie möglich nach dem Entfernen des ausgefallenen Laufwerks. Andernfalls besteht die Gefahr, dass die Ausrüstung überhitzt.


CAUTION: *Möglicher Datenverlust* -- Wenn Sie die Laufwerksschublade wieder in das Gehäuse schieben, schlagen Sie die Schublade niemals zu. Schieben Sie die Schublade langsam hinein, um zu vermeiden, dass die Schublade einrastet und das Speicher-Array beschädigt wird.

.Schritte
. Den Nockengriff am neuen Antrieb senkrecht anheben.
. Richten Sie die beiden angehobenen Tasten auf beiden Seiten des Laufwerkträgers an der entsprechenden Lücke im Laufwerkskanal auf der Laufwerksschublade aus.
. Senken Sie den Antrieb gerade nach unten, und drehen Sie dann den Nockengriff nach unten, bis das Laufwerk unter dem orangefarbenen Freigaberiegel einrastet.
. Schieben Sie die Laufwerkschublade vorsichtig wieder in das Gehäuse. Schieben Sie die Schublade langsam hinein, um zu vermeiden, dass die Schublade einrastet und das Speicher-Array beschädigt wird.
. Schließen Sie die Antriebsschublade, indem Sie beide Hebel in die Mitte schieben.
+
Die grüne Aktivitäts-LED für das ausgetauschte Laufwerk an der Vorderseite der Laufwerksschublade leuchtet auf, wenn das Laufwerk ordnungsgemäß eingesetzt wird.

+
Je nach Konfiguration rekonstruiert der Controller möglicherweise automatisch Daten auf dem neuen Laufwerk. Wenn im Shelf Hot-Spare-Laufwerke verwendet werden, muss der Controller möglicherweise eine vollständige Rekonstruktion des Hot Spare durchführen, bevor er die Daten auf das ausgetauschte Laufwerk kopieren kann. Durch diesen Rekonstruktionsprozess wird die Zeit erhöht, die zum Abschluss dieses Vorgangs erforderlich ist.





== Schritt 4: Vollständige Laufwerksaustausch

Überprüfen Sie, ob das neue Laufwerk ordnungsgemäß funktioniert.

.Schritte
. Überprüfen Sie die ein/aus-LED und die Warn-LED am ausgetauschten Laufwerk. (Wenn Sie das erste Laufwerk einsetzen, leuchtet die Warn-LED möglicherweise auf. Die LED sollte jedoch innerhalb einer Minute ausgeschaltet werden.)
+
** Die ein/aus-LED leuchtet oder blinkt, und die Warn-LED leuchtet nicht: Zeigt an, dass das neue Laufwerk ordnungsgemäß funktioniert.
** Die ein/aus-LED leuchtet auf: Zeigt an, dass das Laufwerk möglicherweise nicht ordnungsgemäß installiert ist. Entfernen Sie das Laufwerk, warten Sie 30 Sekunden, und installieren Sie es dann wieder.
** Die Warnungs-LED leuchtet: Zeigt an, dass das neue Laufwerk möglicherweise defekt ist. Tauschen Sie es durch ein anderes neues Laufwerk aus.


. Wenn der Recovery Guru im SANtricity System Manager immer noch ein Problem zeigt, wählen Sie *recheck* aus, um sicherzustellen, dass das Problem behoben wurde.
. Wenn der Recovery Guru angibt, dass die Laufwerksrekonstruktion nicht automatisch gestartet wurde, muss die Rekonstruktion manuell gestartet werden wie folgt:
+

NOTE: Führen Sie diesen Vorgang nur aus, wenn Sie vom technischen Support oder dem Recovery Guru dazu aufgefordert werden.

+
.. Wählen Sie *Hardware*.
.. Klicken Sie auf das Laufwerk, das Sie ersetzt haben.
.. Wählen Sie im Kontextmenü des Laufwerks die Option *rekonstruieren*.
.. Bestätigen Sie, dass Sie diesen Vorgang ausführen möchten.
+
Nach Abschluss der Laufwerkswiederherstellung befindet sich die Volume-Gruppe in einem optimalen Zustand.



. Bringen Sie die Blende bei Bedarf wieder an.
. Senden Sie das fehlerhafte Teil wie in den dem Kit beiliegenden RMA-Anweisungen beschrieben an NetApp zurück.


.Was kommt als Nächstes?
Der Austausch des Laufwerks ist abgeschlossen. Sie können den normalen Betrieb fortsetzen.
