---
permalink: sg5700/replacing-e5700sg-controller.html 
sidebar: sidebar 
keywords: storagegrid, sg5700, storage node, storage appliance, Replacing, replace, E5700sg, controller, remove, removing, removal, install, installing, installation 
summary: Möglicherweise müssen Sie den E5700SG-Controller austauschen, wenn er nicht optimal funktioniert oder ausgefallen ist. 
---
= Ersetzen Sie den StorageGRID E5700SG-Rechnercontroller
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie den E5700SG-Controller austauschen, wenn er nicht optimal funktioniert oder ausgefallen ist.

.Bevor Sie beginnen
* Sie verfügen über einen Ersatzcontroller mit derselben Teilenummer wie der zu ersetzenden Controller.
* Sie haben die Anweisungen zur E-Series zum Austausch eines ausgefallenen E5700 Controllers heruntergeladen.
+

NOTE: Weitere Einzelheiten zu bestimmten Schritten finden Sie nur in den Anweisungen zur E-Serie.  Verwenden Sie sie nicht, um einen Controller im StorageGRID -Gerät zu ersetzen, da die Verfahren unterschiedlich sind.  Beispielsweise wird in den Anweisungen der E-Serie für den E5700-Controller beschrieben, wie die Batterie und die Host-Schnittstellenkarte (HIC) aus einem ausgefallenen Controller entfernt und in einem Ersatzcontroller installiert werden.  Diese Schritte gelten nicht für den StorageGRID E5700SG-Controller.

* Sie verfügen über Etiketten, um jedes Kabel, das mit dem Controller verbunden ist, zu identifizieren.


.Über diese Aufgabe
Wenn Sie den Controller austauschen, können Sie nicht mehr auf den Speicherknoten des Geräts zugreifen.  Wenn der E5700SG-Controller ausreichend funktioniert, können Sie zu Beginn dieses Vorgangs ein kontrolliertes Herunterfahren durchführen.


NOTE: Wenn Sie den Controller vor dem Installieren der StorageGRID-Software ersetzen, können Sie nach Abschluss dieses Verfahrens möglicherweise nicht sofort auf den StorageGRID Appliance Installer zugreifen. Sie können zwar von anderen Hosts im selben Subnetz wie die Appliance auf das Installationsprogramm der StorageGRID-Appliance zugreifen, können jedoch nicht von Hosts in anderen Subnetzen darauf zugreifen. Diese Bedingung sollte sich innerhalb von 15 Minuten lösen (wenn Einträge im ARP-Cache für die ursprüngliche Controller-Zeit erforderlich sind), oder Sie können den Zustand sofort löschen, indem Sie alle alten ARP-Cacheeinträge manuell vom lokalen Router oder Gateway löschen.

.Schritte
. Fahren Sie den E5700SG Controller herunter.
+
.. Melden Sie sich beim Grid-Node an:
+
... Geben Sie den folgenden Befehl ein: `ssh admin@_grid_node_IP_`
... Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
... Geben Sie den folgenden Befehl ein, um zum Root zu wechseln: `su -`
... Geben Sie das im aufgeführte Passwort ein `Passwords.txt` Datei:
+
Wenn Sie als root angemeldet sind, ändert sich die Eingabeaufforderung von `$` Bis `#`.





. Fahren Sie den E5700SG-Controller herunter:*`shutdown -h now` *
. Wenn die mit dem Controller verbundenen StorageGRID-Netzwerke DHCP-Server verwenden:
+
.. Beachten Sie die MAC-Adressen für die Ports am Ersatz-Controller (auf Etiketten am Controller).
.. Bitten Sie den Netzwerkadministrator, die IP-Adresseinstellungen für den ursprünglichen Controller zu aktualisieren, um die MAC-Adressen für den Ersatz-Controller zu reflektieren.
+

CAUTION: Sie müssen sicherstellen, dass die IP-Adressen für den Original-Controller aktualisiert wurden, bevor Sie den Ersatz-Controller in das Gerät einsetzen.  Andernfalls erhält der Controller beim Booten neue DHCP-IP-Adressen und kann möglicherweise keine erneute Verbindung zu StorageGRID herstellen.  Dieser Schritt gilt für alle StorageGRID -Netzwerke, die an den Controller angeschlossen sind.



. Entfernen Sie den Controller aus dem Gerät:
+
.. Setzen Sie ein ESD-Armband an oder ergreifen Sie andere antistatische Vorsichtsmaßnahmen.
.. Beschriften Sie die Kabel, und trennen Sie dann die Kabel und SFPs.
+

NOTE: Um eine verminderte Leistung zu vermeiden, dürfen die Kabel nicht verdreht, gefaltet, gequetscht oder treten.

.. Lösen Sie die Steuerung vom Gerät, indem Sie die Verriegelung am Nockengriff so lange drücken, bis sie sich löst, und öffnen Sie dann den Nockengriff nach rechts.
.. Schieben Sie den Regler mit zwei Händen und dem Nockengriff aus dem Gerät.
+

CAUTION: Verwenden Sie immer zwei Hände, um das Gewicht der Steuerung zu unterstützen.



. Setzen Sie den Ersatzcontroller in das Gerät ein.
+
.. Drehen Sie den Controller um, so dass die abnehmbare Abdeckung nach unten zeigt.
.. Schieben Sie den Steuerknebel in die geöffnete Stellung, und schieben Sie ihn bis zum Gerät.
.. Bewegen Sie den Nockengriff nach links, um die Steuerung zu verriegeln.
.. Ersetzen Sie die Kabel und SFPs.


. Nachdem die Controller erfolgreich gestartet wurden, sollten in den sieben Segment-Displays folgende Werte angezeigt werden:
+
** Controller der E2800 Serie:
+
Der endgültige Zustand ist `99`.

** E5700SG Controller:
+
Der endgültige Zustand ist `HA`.



. Nachdem das Gerät wieder dem Grid beigetreten ist, vergewissern Sie sich, dass der Speicherknoten des Geräts im Grid Manager angezeigt wird und dass keine Alarme auftreten.


Nach dem Austausch des Teils senden Sie das fehlerhafte Teil an NetApp zurück, wie in den mit dem Kit gelieferten RMA-Anweisungen beschrieben. Siehe https://mysupport.netapp.com/site/info/rma["Teilerückgabe  Austausch"^] Seite für weitere Informationen.

.Verwandte Informationen
https://docs.netapp.com/us-en/e-series-family/index.html["Dokumentation zur NetApp E-Series"^]
