---
permalink: commonhardware/how-appliance-node-cloning-works.html 
sidebar: sidebar 
keywords: storagegrid, appliance node cloning, appliance node clone 
summary: Sie können einen Appliance-Node in StorageGRID klonen, um eine Appliance mit neuerem Design oder höheren Funktionen zu verwenden. Durch das Klonen werden alle Informationen über den vorhandenen Node an die neue Appliance übertragen, ein einfach zu durchsetzender Hardware-Upgrade-Prozess bietet eine Alternative zur Ausmusterung und Erweiterung beim Austausch von Appliances. 
---
= Wie das Klonen von StorageGRID-Appliance-Knoten funktioniert
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können einen Appliance-Node in StorageGRID klonen, um eine Appliance mit neuerem Design oder höheren Funktionen zu verwenden. Durch das Klonen werden alle Informationen über den vorhandenen Node an die neue Appliance übertragen, ein einfach zu durchsetzender Hardware-Upgrade-Prozess bietet eine Alternative zur Ausmusterung und Erweiterung beim Austausch von Appliances.

Mit dem Appliance-Node-Klonen können Sie einen vorhandenen Appliance-Node (Quelle) im Grid ganz einfach durch eine kompatible Appliance (Ziel) ersetzen, die Teil desselben logischen StorageGRID-Standorts ist. Dabei werden alle Daten auf die neue Appliance übertragen, die Appliance wird in Betrieb versetzt, um den alten Appliance-Node zu ersetzen und die alte Appliance im Installationszustand zu lassen.



== Warum einen Appliance-Node klonen?

Sie können einen Appliance-Node klonen, wenn Sie Folgendes benötigen:

* Ersetzen Sie Appliances, die sich dem Ende ihrer Lebensdauer nähert.
* Aktualisieren Sie vorhandene Nodes, um von der verbesserten Appliance-Technologie zu profitieren.
* Erhöhen Sie die Grid-Storage-Kapazität, ohne die Anzahl der Storage-Nodes in Ihrem StorageGRID System zu ändern.
* Verbessern Sie die Storage-Effizienz, z. B. durch Ändern des RAID-Modus von DDP-8 auf DDP-16 oder auf RAID-6.
* Node-Verschlüsselung wird effizient implementiert, sodass die externen Verschlüsselungsmanagement-Server (KMS) verwendet werden können.




== Welches StorageGRID Netzwerk wird verwendet?

Durch das Klonen werden Daten vom Quell-Node über ein beliebiges StorageGRID-Netzwerk direkt an die Ziel-Appliance übertragen. Das Grid-Netzwerk wird normalerweise verwendet, Sie können aber auch das Admin-Netzwerk oder das Client-Netzwerk verwenden, wenn die Quell-Appliance mit diesen Netzwerken verbunden ist. Wählen Sie das Netzwerk für den Klon-Traffic aus, das die beste Performance bei der Datenübertragung bietet, ohne die Leistung des StorageGRID-Netzwerks oder die Datenverfügbarkeit zu beeinträchtigen.

Bei der Installation der Ersatzanwendung müssen Sie temporäre IP-Adressen für StorageGRID-Verbindung und Datentransfer angeben. Da die Ersatz-Appliance Teil derselben Netzwerke ist wie der Appliance-Node, den sie ersetzt, müssen Sie für jedes dieser Netzwerke auf der Ersatz-Appliance temporäre IP-Adressen angeben.



== Welche Informationen sind nicht geklont?

Die folgenden Appliance-Konfigurationen werden beim Klonen nicht auf die Ersatz-Appliance übertragen. Sie müssen sie bei der Ersteinrichtung des Ersatzgeräts konfigurieren.

* BMC Schnittstelle
* Netzwerkverbindungen
* Verschlüsselungsstatus der Nodes
* SANtricity System Manager (für Storage-Nodes)
* RAID-Modus (für Storage-Nodes)




== Welche Probleme verhindern das Klonen?

Wenn beim Klonen eines der folgenden Probleme auftreten, stoppt der Klonprozess und eine Fehlermeldung wird erzeugt:

* Falsche Netzwerkkonfiguration
* Fehlende Konnektivität zwischen Quell- und Ziel-Appliances
* Nicht kompatibel mit Quell- und Ziel-Appliance
* Bei Storage-Nodes eine Ersatz-Appliance mit unzureichender Kapazität


Sie müssen jedes Problem lösen, damit das Klonen fortgesetzt werden kann.



== Kompatibilität der Ziel-Appliance

Ersatz-Appliances müssen vom gleichen Typ sein wie der Quell-Node, den sie ersetzen, und beide müssen Teil desselben logischen StorageGRID-Standorts sein.

Lesen Sie vor dem Klonen die allgemeinen Klonüberlegungen sowie die spezifischen Kloninformationen und -Einschränkungen für die einzelnen Appliance-Typen durch.



=== Allgemeine Überlegungen zum Klonen von Services-Appliances

* Eine Ersatzdienstanwendung kann ein anderes Modell sein als der Admin-Node oder der Gateway-Node, den sie ersetzt.
* Die Services-Appliances haben unterschiedliche Netzwerkanschlüsse. Wenn Sie den Gerätetyp ändern, müssen möglicherweise die Kabel oder SFP-Module ersetzt werden.




=== Allgemeine Überlegungen zum Klonen von Storage Appliances

* Eine Ersatzspeichergerät muss über eine größere Kapazität verfügen als der zu ersetzende Speicher-Node.
+
** Wenn die Ziel-Storage-Appliance über dieselbe Anzahl von Laufwerken wie der Quell-Node verfügt, müssen die Laufwerke in der Ziel-Appliance über eine größere Kapazität (in TB) verfügen.
** Wenn Sie planen, auf dem Zielknoten denselben RAID-Modus wie auf dem Quellknoten zu verwenden, Oder in einem weniger Storage-effizienten RAID-Modus (z. B. Wechsel von RAID 6 zu DDP) müssen die Laufwerke in der Ziel-Appliance größer (in TB) sein als die Laufwerke in der Quell-Appliance.
** Die Anzahl der Volumes in einem Zielspeichergerät muss mindestens der Anzahl der Volumes im Quellknoten entsprechen. Das SGF6112 verfügt über 12 Volumes, das SGF6212 über 13 Volumes. Alle anderen Speichergeräte haben 16 Volumes.
** Ausnahmen zu den allgemeinen Überlegungen zum Klonen von Storage Appliances sind:
+
*** Wenn die Anzahl der in einer Ziel-Storage-Appliance installierten Standardlaufwerke aufgrund der Installation von Solid-State-Laufwerken (SSDs) geringer ist als die Anzahl der Laufwerke im Quell-Node, ist die allgemeine Storage-Kapazität der Standardlaufwerke in der Ziel-Appliance (in TB) Muss die gesamte funktionale Laufwerkskapazität aller Laufwerke im Quell-Storage-Node überschreiten.
+
Wenn Sie beispielsweise eine SG5760 Quell-Storage-Node-Appliance mit 60 Laufwerken auf eine SG6060 Ziel-Appliance mit 58 Standardlaufwerken klonen, sollten Sie vor dem Klonen in der SG6060 Ziel-Appliance größere Laufwerke installieren, um die Storage-Kapazität aufrechtzuerhalten. (Die zwei Laufwerksschächte, die SSDs in der Ziel-Appliance enthalten, sind nicht in der gesamten Appliance-Storage-Kapazität enthalten.)

+
Wenn jedoch eine SG5760 Quell-Node-Appliance für 60 Laufwerke mit SANtricity Dynamic Disk Pools DDP-8 (DDP) konfiguriert ist, kann die SG6060 Appliance für 58 Laufwerke mit DDP-16 aufgrund der verbesserten Storage-Effizienz ein gültiges Klonziel für die SG6060 Appliance werden.

+
Informationen zum aktuellen RAID-Modus des Quellgeräteknotens finden Sie auf der Seite *Knoten* im Grid Manager. Wählen Sie die Registerkarte *Speicher* für das Gerät aus.

*** Sie können einen Quellknoten mit 16 Objektspeicher-Volumes (rangedb) nicht auf ein Zielspeichergerät mit weniger Objektspeicher-Volumes klonen, selbst wenn das Zielgerät eine größere Kapazität als der Quellknoten hat.








=== Informationen und Einschränkungen zum Klonen der SG100 Appliance

Sie können eine SG100 Quell-Node-Appliance auf einer SG110-, SG1000- oder SG1100-Services-Ziel-Appliance klonen. Durch das Klonen der SG100 auf eine SG1000- oder SG1100-Services-Ziel-Appliance kann der Admin-Node oder Gateway-Node mehr Funktionen erhalten.



=== Informationen und Einschränkungen zum Klonen von SG110-Appliances

Sie können eine SG110-Quell-Node-Appliance auf ein SG1100-Services-Appliance-Ziel klonen, um dem Admin-Node oder Gateway-Node eine höhere Kapazität zu geben.

Das Klonen von Knoten von einer SG110-Quellknoten-Appliance ohne Knotenverschlüsselung auf ein SG110-Appliance-Ziel mit Knotenverschlüsselung wird nicht unterstützt.



=== Informationen und Einschränkungen zum Klonen des SG120-Geräts

Sie können eine SG120-Quellknoten-Appliance auf eine SG1200-Services-Appliance als Ziel klonen, um dem Admin Node oder Gateway Node mehr Funktionalität zu verleihen.

Das Klonen von Knoten wird von einer SG120-Quellknoten-Appliance ohne Knotenverschlüsselung zu einer SG120-Appliance-Ziel mit Knotenverschlüsselung nicht unterstützt.



=== Informationen und Einschränkungen zum Klonen von SG1000 Appliances

Sie können eine SG1000 Quell-Node-Appliance auf einer SG100-, SG110- oder SG1100-Services-Ziel-Appliance klonen.

* Durch das Klonen der SG1000 in eine SG100- oder SG110-Services-Ziel-Appliance können Sie die SG1000 für eine anspruchsvollere Applikation implementieren.
* Durch den Austausch einer SG1000-Quell-Node-Appliance durch eine SG100-Services-Ziel-Appliance wird die maximale Geschwindigkeit der Netzwerkports von 100 GbE auf 25 GbE verringert.




=== SG1100 Appliance zum Klonen von Informationen und Einschränkungen

Sie können eine SG1100 Quell-Node-Appliance auf eine SG110 Services-Ziel-Appliance klonen.

* Durch das Klonen der SG1100 in eine SG110-Services-Ziel-Appliance können Sie die SG1100 für eine anspruchsvollere Applikation neu implementieren. Wenn beispielsweise eine SG1100-Quell-Node-Appliance als Admin-Node verwendet wird und Sie sie als dedizierten Load-Balancing-Node verwenden möchten.
* Wenn Sie eine SG1100-Quell-Node-Appliance durch eine SG110-Services-Ziel-Appliance ersetzen, wird die maximale Geschwindigkeit der Netzwerk-Ports von 100 GbE auf 25 GbE reduziert.


Das Klonen von Knoten von einer SG1100-Quellknoten-Appliance ohne Knotenverschlüsselung auf ein SG1100-Appliance-Ziel mit Knotenverschlüsselung wird nicht unterstützt.



=== Informationen und Einschränkungen zum Klonen des SG1200-Geräts

Sie können eine SG1200-Quellknoten-Appliance auf eine SG120-Services-Ziel-Appliance klonen.

* Durch das Klonen der SG1200 auf eine SG120-Services-Ziel-Appliance können Sie die SG1200 für eine anspruchsvollere Anwendung neu bereitstellen. Beispielsweise, wenn eine SG1200-Source-Node-Appliance als Admin Node verwendet wird und Sie sie als dedizierten Load-Balancing-Node einsetzen möchten.
* Durch den Austausch eines SG1200-Quellknotengeräts gegen ein SG120-Dienstzielgerät wird die maximale Geschwindigkeit der Netzwerkports von 100-GbE auf 25-GbE reduziert.


Das Klonen von Knoten wird von einer SG1200-Quellknoten-Appliance ohne Knotenverschlüsselung zu einer SG1200-Appliance-Ziel mit Knotenverschlüsselung nicht unterstützt.



=== SG5712 Informationen und Einschränkungen zum Klonen von Appliances

Sie können eine mit DDP konfigurierte SG5712-Quell-Node-Appliance in einer SG5812-Storage-Ziel-Appliance klonen.



=== Informationen und Einschränkungen zum Klonen der SG5760 Appliance

* Sie können eine mit DDP16 konfigurierte SG5760-Quell-Node-Appliance in einer mit DDP16 konfigurierten SG5860-Storage-Ziel-Appliance klonen.
* Eine SG5760-Quell-Node-Appliance, die mit DDP konfiguriert ist, kann nicht auf eine SG5860-Storage-Ziel-Appliance geklont werden, die mit DDP konfiguriert ist.
* Ein SG5760-Quellknotengerät, das mit DDP oder DDP-16 konfiguriert ist, _kann nicht_ auf ein SG6160- oder SG6260-Speicherzielgerät mit passendem RAID-Modus geklont werden.




=== SG5812 Appliance zum Klonen von Informationen und Einschränkungen

Sie können eine SG5812-Appliance erfolgreich als Quelle oder Ziel klonen.



=== SG5860 Appliance zum Klonen von Informationen und Einschränkungen

Sie können eine SG5860-Appliance erfolgreich als Quelle oder Ziel mit einigen Einschränkungen klonen (siehe Informationen zum Klonen der Appliance und Einschränkungen für jede Quelle).



=== Informationen und Einschränkungen zum Klonen der SG6060 Appliance

* Sie können eine SG6060-Quell-Node-Appliance, die mit DDP oder DDP16 konfiguriert ist, in einem passenden RAID-Modus auf eine SG5860-Storage-Ziel-Appliance klonen.
* Sie können ein SG6060-Quellknotengerät ohne Erweiterungsgehäuse auf ein SG6160- oder SG6260-Speicherzielgerät ohne Erweiterungsgehäuse klonen, wenn die Laufwerksgrößen und RAID-Modi identisch sind.
* Ein SG6060-Quellknotengerät mit beliebiger Anzahl von Erweiterungsgehäusen _kann nicht_ auf ein SG6160- oder SG6260-Speicherzielgerät geklont werden, selbst wenn die Anzahl der Erweiterungsgehäuse, die Laufwerksgrößen und die RAID-Modi gleich sind.




=== Informationen und Einschränkungen zum Klonen von SGF6112-Geräten

Das Klonen von Knoten wird von einer SGF6112-Quellknoten-Appliance ohne Knotenverschlüsselung auf eine SGF6112- oder SGF6212-Appliance als Ziel mit Knotenverschlüsselung nicht unterstützt.



=== Informationen und Einschränkungen zum Klonen der SG6160- und SG6260-Appliances

Sie können eine SG6160-Appliance mit einigen Einschränkungen erfolgreich als Quelle oder Ziel klonen (siehe Informationen zum Klonen der Appliance und Einschränkungen für jede Quelle).
